#include "maingamewindow.h"
#include "ui_maingamewindow.h"

//adds buttons into a vector for easier access
void MainGameWindow::addbuttons(){
    gridbuttons.push_back(uigame->b00);
    gridbuttons.push_back(uigame->b01);
    gridbuttons.push_back(uigame->b02);
    gridbuttons.push_back(uigame->b03);
    gridbuttons.push_back(uigame->b04);
    gridbuttons.push_back(uigame->b05);
    gridbuttons.push_back(uigame->b06);
    gridbuttons.push_back(uigame->b07);
    gridbuttons.push_back(uigame->b08);
    gridbuttons.push_back(uigame->b10);
    gridbuttons.push_back(uigame->b11);
    gridbuttons.push_back(uigame->b12);
    gridbuttons.push_back(uigame->b13);
    gridbuttons.push_back(uigame->b14);
    gridbuttons.push_back(uigame->b15);
    gridbuttons.push_back(uigame->b16);
    gridbuttons.push_back(uigame->b17);
    gridbuttons.push_back(uigame->b18);
    gridbuttons.push_back(uigame->b20);
    gridbuttons.push_back(uigame->b21);
    gridbuttons.push_back(uigame->b22);
    gridbuttons.push_back(uigame->b23);
    gridbuttons.push_back(uigame->b24);
    gridbuttons.push_back(uigame->b25);
    gridbuttons.push_back(uigame->b26);
    gridbuttons.push_back(uigame->b27);
    gridbuttons.push_back(uigame->b28);
    gridbuttons.push_back(uigame->b30);
    gridbuttons.push_back(uigame->b31);
    gridbuttons.push_back(uigame->b32);
    gridbuttons.push_back(uigame->b33);
    gridbuttons.push_back(uigame->b34);
    gridbuttons.push_back(uigame->b35);
    gridbuttons.push_back(uigame->b36);
    gridbuttons.push_back(uigame->b37);
    gridbuttons.push_back(uigame->b38);
    gridbuttons.push_back(uigame->b40);
    gridbuttons.push_back(uigame->b41);
    gridbuttons.push_back(uigame->b42);
    gridbuttons.push_back(uigame->b43);
    gridbuttons.push_back(uigame->b44);
    gridbuttons.push_back(uigame->b45);
    gridbuttons.push_back(uigame->b46);
    gridbuttons.push_back(uigame->b47);
    gridbuttons.push_back(uigame->b48);
    gridbuttons.push_back(uigame->b50);
    gridbuttons.push_back(uigame->b51);
    gridbuttons.push_back(uigame->b52);
    gridbuttons.push_back(uigame->b53);
    gridbuttons.push_back(uigame->b54);
    gridbuttons.push_back(uigame->b55);
    gridbuttons.push_back(uigame->b56);
    gridbuttons.push_back(uigame->b57);
    gridbuttons.push_back(uigame->b58);
    gridbuttons.push_back(uigame->b60);
    gridbuttons.push_back(uigame->b61);
    gridbuttons.push_back(uigame->b62);
    gridbuttons.push_back(uigame->b63);
    gridbuttons.push_back(uigame->b64);
    gridbuttons.push_back(uigame->b65);
    gridbuttons.push_back(uigame->b66);
    gridbuttons.push_back(uigame->b67);
    gridbuttons.push_back(uigame->b68);
    gridbuttons.push_back(uigame->b70);
    gridbuttons.push_back(uigame->b71);
    gridbuttons.push_back(uigame->b72);
    gridbuttons.push_back(uigame->b73);
    gridbuttons.push_back(uigame->b74);
    gridbuttons.push_back(uigame->b75);
    gridbuttons.push_back(uigame->b76);
    gridbuttons.push_back(uigame->b77);
    gridbuttons.push_back(uigame->b78);

}
